#!/usr/bin/env php
<?php

// Usage
// php install

$env = $argv[1] ?? 'dev';

if (file_exists('./composer.lock') && in_array('reset', $argv)) {
    shell_exec('rm -f ./composer.lock');
}

if (file_exists('./package-lock.json') && in_array('reset', $argv)) {
    shell_exec('rm -f /.package-lock.json');
}

if (file_exists('./vendor') && in_array('reset', $argv)) {
    shell_exec('rm -rf ./vendor');
}

if (file_exists('./node_modules') && in_array('reset', $argv)) {
    shell_exec('rm -rf ./node_modules');
    shell_exec('npm cache clean -f');
}

$install = in_array('upgrade', $argv)? 'upgrade': 'install';

shell_exec("composer $install");
shell_exec("npm $install");

shell_exec('npm ' . $env);
