---
Name: myapp
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension

SilverStripe\Assets\Image:
  extensions:
    - ImageExtension
SilverStripe\Assets\Storage\DBFile:
  extensions:
    - ImageExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\AssetAdmin\Helper\ImageThumbnailHelper:
    constructor:
      0: 0
  Intervention\Image\ImageManager:
  constructor:
    - { driver: imagick }
Page:
  extensions:
    - CustomShortCodes
