---
Name: myapp
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension

SilverStripe\Assets\Image:
  extensions:
    - ImageExtension
Page:
  extensions:
    - CustomShortCodes
