mappings:
  ImageGalleryAlbum: TractorCow\ImageGallery\Model\ImageGalleryAlbum
  ImageGalleryImage: TractorCow\ImageGallery\Model\ImageGalleryImage
  ImageGalleryItem: TractorCow\ImageGallery\Model\ImageGalleryItem
  ImageGallerySiteTree: TractorCow\ImageGallery\Extensions\ImageGallerySiteTree
  ImageGalleryPage: TractorCow\ImageGallery\Pages\ImageGalleryPage
  ImageGalleryPage_Controller: TractorCow\ImageGallery\Pages\ImageGalleryPageController
  UpdateImageGalleryTask: TractorCow\ImageGallery\Tasks\UpdateImageGalleryTask
